# [[main]]
#   name = 'Home'
#   pageRef = '/'
#   weight = 10

[[main]]
  name = 'About'
  pageRef = '/about'
  weight = 50

[[main]]
  name = 'Search'
  pageRef = '/search'
  weight = 55

[[main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 60

[[main]]
  name = 'Events'
  pageRef = '/events'
  weight = 70

[[main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 80

[[main]]
  name = 'Categories'
  pageRef = '/categories'
  weight = 90

[[main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 100
