baseURL = 'https://lemon73-computing.github.io/'
DefaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
title = 'Lemonium'

enableGitInfo = true

[languages]
  [languages.en]
    weight = 10
    languageName = "English"
    languageCode = 'en-us'
    contentDir = 'content/en'

  [languages.ja]
    weight = 20
    languageName = "Japanese"
    languageCode = 'ja-jp'
    contentDir = 'content/ja'
    hasCJKLanguage = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[services]
  [services.googleAnalytics]
    id = 'G-29B1VSEP30'
