name: Article request
description: Suggest an idea for article
title: "[docs]: "
labels: [documentation]

body:
- type: textarea
  attributes:
    label: Describe the article you'd like
    description: A clear and concise description of what you want to add article.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the article request here.
  validations:
    required: false
