blank_issues_enabled: true
contact_links:
  - name: Docs / 資料
    url: https://github.com/AliceNovel/Docs/issues/new
    about: Issue for docs / 資料に関する意見
  - name: Sample / サンプル
    url: https://github.com/AliceNovel/SampleGames/issues/new
    about: Issue for sample games / サンプルゲームに関する意見
